### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jamacku** [lzaoral/defloc#1]
I like this utility, It works great do you plan to package it in Fedora?

**Comment by lzaoral** [comment]
Thanks for the positive feedback, @jamacku!  It's already available in [COPR](https://copr.fedorainfracloud.org/coprs/lzaoral/defloc/) but I agree that the COPR badge in the README file is very easy to miss.

edit: typo

**Comment by jamacku** [comment]
I didn't miss the COPR badge. :) I wanted to just ask if you were thinking about adding a package to Fedora, It would be "easier" to install and more people could start using it. But I know that it's a lot of hassle to do it and maintain it there. COPR works for me perfektly! :+1:
